l = float (input("Enter the length of the cuboid:"))
b = float (input("Enter the breadth of the cuboid:"))
h = float (input("Enter the height of the cuboid:"))
area = 2*((l*b) + (l*h) + (b*h))
print("The Total surface area of the cuboid is: ", area)
